"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Doctors",
      [
        {
          name: "Dr. Amit Sharma",
          email: "amit.sharma@example.com",
          phone: "9876543210",
          category_id: 1,
          details: "MBBS, MD - Cardiology. Experienced in heart surgeries.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Neha Verma",
          email: "neha.verma@example.com",
          phone: "9123456780",
          category_id: 2,
          details: "MBBS, MS - Orthopedics. Specialist in joint replacement.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Rajesh Kumar",
          email: "rajesh.kumar@example.com",
          phone: "9988776655",
          category_id: 1,
          details: "MBBS, MD - Cardiology. Expert in pediatric cardiology.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Priya Singh",
          email: "priya.singh@example.com",
          phone: "9112233445",
          category_id: 3,
          details: "MBBS, MS - Dermatology. Specialist in skin treatments.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Sanjay Gupta",
          email: "sanjay.gupta@example.com",
          phone: "9234567890",
          category_id: 2,
          details: "MBBS, MS - Orthopedics. Focus on sports injuries.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Anjali Mehra",
          email: "anjali.mehra@example.com",
          phone: "9345678901",
          category_id: 3,
          details: "MBBS, MD - Dermatology. Expert in cosmetic dermatology.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Rakesh Yadav",
          email: "rakesh.yadav@example.com",
          phone: "9456789012",
          category_id: 1,
          details: "MBBS, MD - Cardiology. Specializes in heart failure.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Kavita Joshi",
          email: "kavita.joshi@example.com",
          phone: "9567890123",
          category_id: 2,
          details: "MBBS, MS - Orthopedics. Pediatric orthopedic specialist.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Vivek Malhotra",
          email: "vivek.malhotra@example.com",
          phone: "9678901234",
          category_id: 3,
          details: "MBBS, MD - Dermatology. Known for laser treatments.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Sonali Kapoor",
          email: "sonali.kapoor@example.com",
          phone: "9789012345",
          category_id: 1,
          details:
            "MBBS, MD - Cardiology. Expert in interventional cardiology.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Mohit Jain",
          email: "mohit.jain@example.com",
          phone: "9890123456",
          category_id: 2,
          details: "MBBS, MS - Orthopedics. Joint replacement surgeries.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Neeta Sharma",
          email: "neeta.sharma@example.com",
          phone: "9901234567",
          category_id: 3,
          details: "MBBS, MD - Dermatology. Skin allergy specialist.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Arjun Singh",
          email: "arjun.singh@example.com",
          phone: "9912345678",
          category_id: 1,
          details: "MBBS, MD - Cardiology. Focus on preventive cardiology.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Ritu Verma",
          email: "ritu.verma@example.com",
          phone: "9923456789",
          category_id: 2,
          details: "MBBS, MS - Orthopedics. Trauma and accident cases.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dr. Pooja Kapoor",
          email: "pooja.kapoor@example.com",
          phone: "9934567890",
          category_id: 3,
          details: "MBBS, MD - Dermatology. Specializes in acne treatments.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Doctors", null, {});
  },
};
